# Pull base image.
FROM openjdk:8
MAINTAINER HMF Team

ADD dcc-release-client/target/dcc-release-client-5.1.2-SNAPSHOT.jar /opt/
ADD dcc-release-core/target/test-classes/fixtures/dictionary.json.gz /opt/
ADD dcc-release-core/target/test-classes/fixtures/codelists.json.gz /opt/
